apiVersion: v1
kind: Service
metadata:
    name: tfm-backend
spec:
    ports:
    - port: 80
      targetPort: 3000
    selector:
      app: tfm-backend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-backend
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: tfm-backend
          servicePort: 80
